# Generated by Django 3.0.2 on 2021-04-04 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='create_datetime',
            new_name='created_datetime',
        ),
    ]
